### PR TITLE
Comproperty247 patch 1

### PR DESCRIPTION
**Pull request by comproperty247**
This will allow to deny or add permissions to access to component in Administration side.
After uploading this 2 files to your site, goto YOURSITE/administrator/index.php?option=com_config&view=component&component=com_bfstop

2 options will appear:
- Configure ACL & Options
- Access Administration Interface

### CODE REVIEW

**Comment by comproperty247** [comment]
I am not very familiar with github and to do a pull request for the 2 files I just uploaded.
My main idea is just to add access.xml and config.xml to bfstop.
The 3 files helper....php, not sure why they appear also in the pull request!! :-/
I hope this will fulfill a new option in admin side.
Regards

**Comment by codeling** [comment]
Thanks very much, sounds like a useful thing to add!

> The 3 files helper....php, not sure why they appear also in the pull request!! :-/

You changed them with the commits mentioned in the "Commits" tab:
74e8ddd23d67f905678d3a40386a4c12eed60de4 ("Avoid full scan on users table") and b60d9da97b289bc35b2b9e144049b439eafb949f ("adding defined( '_JEXEC' ) or die;"), both from March 4th 2013. 
Apparently you haven't updated your repository (https://github.com/comproperty247/bfstop) to reflect my repository (https://github.com/codeling/bfstop). Those helper.xyz.php files don't even exist anymore in my repository.
You have two options: (1) Either pull the changes from my repository (but you'd probably have to rebase, which is not that straight-forward; you could try `git pull --rebase` in your repository, but there might be problems/conflicts!), or (2) (probably easier), save the two new files somewhere else, delete your repository, fork mine again, and then do another commit & pull request. Check github help for more information.

Or option (3), I could just add those two files myself ;). Let me know if you choose that option ;)

**Comment by comproperty247** [comment]
Hi,
I will try to delete my repository (option 2) get yours last code and then send the 2 files.
This 2 files are very useful, because can let accees to bfstop to only super admins for example ;-)
Any extra group in admin site will not have any option to see or access to it

**Comment by comproperty247** [comment]
I create a new repository and uploaded the 2 files in it.
Make a pull request and now you should have the things right.
You can try to upload the files and see the result ;-)

**Comment by codeling** [comment]
Thanks! Closing this in favor of https://github.com/codeling/bfstop/pull/120

**Pull request closed without merging**
